import fs from 'node:fs/promises';
const layout = JSON.parse(await fs.readFile('src/data/scenery/town-layout.json', 'utf8'));
const encoded = JSON.stringify(layout.cameras).replaceAll('<', '\\u003c');
await fs.writeFile(
  'artifacts/scenery/review.html',
  `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Malandrins · Scenery review</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f2eee5;color:#253831;font:15px system-ui,sans-serif}header{padding:24px 4vw;background:#243a32;color:#f3ead5;display:flex;justify-content:space-between;align-items:center;gap:24px}header a{color:#e7cb8c}small{letter-spacing:.15em;font-size:10px;text-transform:uppercase}h1{font-size:27px;line-height:1.15;font-weight:550;margin:7px 0}main{max-width:1260px;margin:auto;padding:24px}nav{display:flex;align-items:center;gap:10px;margin-bottom:16px}button,select{border:1px solid #b4b5a5;background:#fbf8ef;color:inherit;padding:11px;border-radius:4px;font:inherit;cursor:pointer}select{flex:1;min-width:0}.pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:0;background:#e2ded3;border:1px solid #c4c1b3}figure img{width:100%;height:min(70vh,850px);object-fit:contain;display:block;background:#d3d6cc}figcaption{padding:11px 15px;display:flex;justify-content:space-between;font-size:12px}#note{color:#637064;font-size:13px;margin:16px 0}footer{display:flex;justify-content:space-between;gap:20px;border-top:1px solid #c9c8b9;padding-top:16px;color:#677166;font-size:12px}a{color:#405e4e}details{margin-top:25px}details img{display:block;width:100%;margin-top:15px}summary{cursor:pointer}p{line-height:1.5}@media(max-width:650px){header{padding:20px;display:block}.pair{gap:8px}main{padding:14px}figure img{height:auto}figcaption{padding:8px;font-size:10px}footer{display:block}h1{font-size:23px}}</style></head>
<body><header><div><small>Malandrins · Town reconstruction</small><h1>La Pobla, from reference to game.</h1></div><a href="../../">Play the rebuilt town ↗</a></header><main>
<nav><button id="previous" aria-label="Previous view">←</button><select id="views" aria-label="Reference viewpoint"></select><button id="next" aria-label="Next view">→</button></nav>
<div class="pair"><figure><figcaption>STREET VIEW REFERENCE <span id="number"></span></figcaption><img id="reference" alt="Original Street View reference"></figure><figure><figcaption>LOW-POLY RECONSTRUCTION <a id="live" target="_blank">Open live view ↗</a></figcaption><img id="game" alt="Reconstructed game from the same recorded camera"></figure></div>
<p id="note"></p><footer><span>${layout.buildings.length} building sections · 5 Blender landmarks<br>Recorded position and direction; camera height and lens estimated.<br>Characters and collectibles are hidden in comparison views.</span><span>Source screenshots: © Google, attribution retained.<br>Aerial layout and land cover: PNOA / IGN-CNIG, CC BY 4.0 scne.es.<br>Building divisions, heights and unseen facades are approximations.</span></footer>
<details><summary>Inspect the building footprints against the aerial reference</summary><img src="layout-aerial-review.jpg" alt="Reconstructed building footprints over the PNOA aerial image"><p>Gold outlines show building sections; cyan marks the five modeled landmarks. PNOA aerial reference, traced and annotated. CC BY 4.0 scne.es — IGN/CNIG.</p></details>
</main><script>
const views=${encoded};let index=2;const select=document.querySelector('#views');
for(const [i,v]of views.entries()){const o=document.createElement('option');o.value=i;o.textContent=v.id+' · '+v.title;select.append(o)}
function render(){const v=views[index];select.value=index;document.querySelector('#reference').src='../../references/google-street-view/'+v.file;document.querySelector('#game').src='view-'+v.id+'.png';document.querySelector('#number').textContent=(index+1)+' / '+views.length;document.querySelector('#live').href='../../?reference='+v.id;document.querySelector('#note').textContent=v.title+' · Bearing '+v.heading+'° · Pitch '+v.pitch+'°';}
select.onchange=()=>{index=Number(select.value);render()};document.querySelector('#previous').onclick=()=>{index=(index+views.length-1)%views.length;render()};document.querySelector('#next').onclick=()=>{index=(index+1)%views.length;render()};render();
</script></body></html>`,
);
